language: python
dist: xenial
sudo: true

python:
  - 3.11

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pip sync -d

script:
  - pipenv run flake8 .
  - pipenv run pytest
